class ContextError( Exception ):

    pass

#-- END class ContextError --#
